setwd("~")
EPCData <- read.table("downloads/household_power_consumption.txt", sep = ";", header = TRUE, na.strings = "?")
EPCData$Date <- as.Date(EPCData$Date, format = "%d/%m/%Y")
newdata <- subset(EPCData, Date == "2007-02-01" | Date == "2007-02-02")
newdata$DT <- as.POSIXct(paste(newdata$Date, newdata$Time), format = "%Y-%m-%d %H:%M:%S")
setwd("desktop/coursera/ExData_Plotting1")
png(file = "plot2.png", bg = "transparent")
with(newdata, plot(DT, Global_active_power, type = "l", xlab = "", ylab = "Global Active Power (kilowatts)"))
dev.off()